TITLE PROG2-3 (EXE) COPY A 6 BYTE ARRAY INTO A NEW 6 BYTE ARRAY OF DATA
PAGE 60, 132

.MODEL SMALL

.STACK 32

.DATA
    
    ;ORG 10H
    DATA1 DB 25H, 4FH, 85H, 1FH, 2BH, 0C4H
    
    ;ORG 28H
    COPY DB 6 DUP (?)
    
.CODE

    MAIN:
    MOV AX, @DATA
    MOV DS, AX
    
    MOV SI, OFFSET DATA1 ;POINTER TO ORIGINAL ARRAY
    MOV DI, OFFSET COPY  ;POINTER TO THE ARRAY WHICH COPIED DATA WILL BE IN IT
    MOV CX, 06H ;LOOP COUNTER CX = 6
    
    MOV_LOOP:
    MOV AL, [SI]  ;COPY I'TH DATA IN REG AL
    MOV [DI], AL  ;MOVE AL DATA IN NEW ARRAY (DATA WHERE SWAPED)
    INC SI
    INC DI
    DEC CX
    JNZ MOV_LOOP  ; JUMP IF CX != 0
    
    MOV AH, 4CH
    INT 21H
    
    END MAIN
    